{
 "title": "Monitors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GPU Failed Requests (Percentage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gpu_worker_requests_failed_total[5m]))\n/\nsum(rate(gpu_worker_requests_completed_total[5m]) + rate(gpu_worker_requests_failed_total[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Batches Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(batch_scheduler_batches_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Received Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Worker Requests Completed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(gpu_worker_requests_completed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Worker Requests Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(gpu_worker_requests_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}